### ISSUE TITLE
Check whether HDDs already exist in inventory or not before adding them

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/turbofresa#16]
Implement #15 and #9 before this one.

These are the steps involved:

- [x] Call the "get items by features" API endpoint using the serial number
- [ ] If HDD is found, update its data: S/N, WWN, etc... (or don't, maybe use a command line switch to decide and/or ask the user)
- [x] If more than 1 HDD is found, figure out what to do (error out and terminate?)

See also: https://github.com/WEEE-Open/turbofresa/issues/9#issuecomment-430566198

**Comment by e-caste** [comment]
I think we should first implement a database check, then implement adding the new info about the disk formatting with `badblocks` to the db. Assigning this to @TsumiYaku.
Let's begin by formatting only disks that are already in the tarallo database.

**Comment by e-caste** [comment]
Implemented in PR #25
