### ISSUE TITLE
Replace lsblk with peracotta implementation of smartctl

### ISSUE THREAD

**Issue by e-caste** [WEEE-Open/turbofresa#21]
Implement detect_disks() method with peracotta method from [read_smartctl.py](https://github.com/WEEE-Open/peracotta/blob/master/read_smartctl.py)

**Comment by lvps** [comment]
Note that read_smartctl reads smartctl output, but does not detect disks: lsblk may still be needed at least to find the /dev/sdX path. `generate_files.sh` from the peracotta uses lsblk for this task, indeed

**Comment by e-caste** [comment]
@lvps I just thought that, since in the peracotta repo `read_smartctl.py` reads files named `smartctl-dev-sdX.txt`, you could simply take the disk name from there.

**Comment by lvps** [comment]
@e-caste Sure, but what generates these files? It's either generate_files (which seems overkill to me) or we call smartctl on the drives, and we need to know which ones do exist to do that

**Comment by e-caste** [comment]
@lvps Right now we’re using the 5 line implementation of lsblk used in generate_files.sh

**Comment by e-caste** [comment]
The last commits by @TsumiYaku close this issue. (You can also close it automatically by writing "close #21" or "fix #21" in the commit message for example)
