### ISSUE TITLE
Refactor integration with tarallo

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/turbofresa#35]
Initially, search disks on tarallo via their serial number (sn).

* If multiple serial numbers exist, throw an error (this has to be fixed manually).
* If the disk exists, read its code. (Bonus: delete the `erased` feature, because it's not erased yet)
* If the disk doesn't exist, create it in Tarallo and get its code.

After the piallaggio update the disk, three cases exist:

- The disk was piallato without errors, SMART data is good:
    - working = yes
    - data-erased = yes
    - surface-scan = pass
    - smart-data = ok
- The disk was piallato, but there are errors or SMART data says it has failed:
    - working = no
    - data-erased = yes
    - surface-scan = pass
    - smart-data = ok
- Badblocks couldn't piallarlo at all (how to detect this case? No idea, maybe if badblock exits in less than N seconds, or gets stuck longer than N hours and has to be killed? Or from its return value?)
    - working = maybe (that means "unclear", it seems like a no but maybe the IDE cable is damaged or something similar)
    - remove data-erased (the feature should no appear at all, there's no "no" value)
    - remove surface-scan (no feature at all)
    - set smart-data if possible

The last case is... hard to detect. But it happened. If it's too difficult to detect it, don't implement it... it's more like "handle badblocks errors of that kind like that"

**Comment by TsumiYaku** [comment]
@lvps I would like to ask a clarification on how to refactor the integration based on the current workflow (or if we need to modify the workflow itself):
1. smartctl_parser.py returns the list of disks scanned with smartctl and marks them as either working or not
2. the disks that are not working are totally ignored by the rest of the workflow. Should we directly add them to the Tarallo as broken before piallggio? In case of yes, could you give me the list of parameters you would like me to insert?
3. working disks are passed to badblocks and there are two outcomes:
    - Badblocks returns 0: all good, simply load it to Tarallo and we're good to go. This should correspond to the first case you listed
    - Badblocks returns something else: disk is not cleaned because something went wrong. Which of the two remaining cases you listed corresponds to this outcome, the second or the third? In general it seems to correspond to the third, i don't know if we're ever gonna have a case where the disk has been piallato but then stopped working, unless we do another (and maybe redundant) scan using smartctl_parser.

**Comment by lvps** [comment]
Point 2: Yes, add the non-working disks too, and I'd say: try to piallarli, too.
When we get a bix box oh HDDs, we want to inventory them all quickly so we can count them and whatnot and we should also try to erase any broken disk before throwing them in the trash, too. We must keep track of what we received, when, if it works or not, if it was piallato or not.

Point 3: It depends: badblocks may print some errors (when it encounters a damaged sector) and continue. Does it return 0 or something else, in that case?
The main point of the cases I listed is: the second one is for disks that have been erased but we should throw away (they are not reliable enough to place in a computer), the third one is for disks that are hopeless but we couldn't even erase, so we'll have to smash them with an hammer and then dispose of them.
Also note that incorrect IDE jumper settings, faulty cables and similar problems may cause badblocks to fail but the disk is actually working: obviously you can't detect these situations at all but they happened at some point... for this reason it's better to have the disk in the tarallo, with as much accurate information as possible, and let people evaluate it. Not having the disk at all would cause confusion.

**Comment by lvps** [comment]
In the stato primordiale, features are:

* data-erased = None
* surface-scan = None

**Comment by lvps** [comment]
I'll make the schemino

**Comment by lvps** [comment]
I wrote pseudocode (aka Python) instead of a schemino:

```py
devices = read_dev()

# Detect and filter devices
devs_to_erase = []
for dev in devices:
	if not contains_system_partitions(dev):
		devs_to_erase += dev

# Try to read smartctl data
disks_to_erase = []
for dev in devs_to_erase:
	error, data = smartctl(dev)
	
	if error and error == 'SMART data is disabled':
		enable_smart_data(dev)
		error, data = smartctl(dev)
		if error:
			print(f"Cannot read SMART data for {dev}, go check its jumpers or whatever")
	
	disks_to_erase += new disk(dev, data)

# Get their code from tarallo
for disk in disks_to_erase:
	# Also, serial numbers need to be normalized! Some disks have different sn on the label and in their firmware!
	# But that can be fixed. If the sn start with WD-, remove WD- and that's normalization. Make a function for that,
	# we may need to normalize more things. It's ok to store the normalized value only inside the disk object.
	qty, code = tarallo.search_by_sn(disk)
	if qty == 1:
		disk.append(code)
	else if qty >= 2:
		disks_to_erase.remove(disk)
		print(f"Duplicate SN for {disk}, go fix it")

# Update or upload new features
for disk in disks_to_erase:
	if disk.has_code():
		features = tarallo.get_features(disk)
		# The same features as usual
		upload = {}
		for feature_to_upload in ['brand', 'model', 'variant', 'capacity-decibyte', 'spin-rate-rpm', 'sn', 'wwn', 'form-factor-hdd', 'type']:
			if not features.contains(feature_to_upload) and disk.features.contains(feature_to_upload):
				upload[feature_to_upload] += disk.features[feature_to_upload]
		if not upload.empty():
			tarallo.update_features(disk.code, upload)
			printf("I added some features to {disk.code}, go and check them from tarallo (maybe split with product)!")
	else:
		if disk.has_sn():
			tarallo.create_item(disk)
			printf("I create {disk.code}, go and check it from tarallo (maybe split with product)!")


# Now erase
for disk in disks_to_erase:
	# Remove data from previous runs (nothing bad happens if data isn't there)
	tarallo.update_features(disk.code, {"erased": None, "surface-scan": None})
	
	result = badblocks(disk)
	
	switch(result):
		case success_no_bad_sectors:
			tarallo.update_features(disk.code, {
				"working": "yes",
				"data-erased" = "yes",
				"surface-scan" = "pass",
			})
			break
		case success_with_bad_sectors:
			# Erased but has errors
			tarallo.update_features(disk.code, {
				"working": "no",
				"data-erased" = "yes",
				"surface-scan" = "pass",
			})
			break
		case failed:
			# Timed out, badblocks could not write anything at all, disk is 0 bytes, ...
			tarallo.update_features(disk.code, {"working": "maybe"})
			break

		printf(f"Result for {disk}: {result}")

# And parse smart data, to check values this time
for disk in disks_to_erase:
	smart_status = "ok"
	
	# is old: more than X hours on, or Y start-stop counts (values to decide)
	# note that the "hours online" value is sometimes in minutes, or half hours, or other weirdness
	if disk.smart_data.is_old():
		# fail is worse than old, so don't override fail if you reverse the order
		# of these checks
		smart_status = "old"
	
	# is failed: has reallocated sectors or one of the smart attributes reports FAILED
	if disk.smart_data.is_failed():
		printf(f"Big warning: reallocated sectors (or other problem) in {disk}")
		smart_status = "fail"
		# The value that you set previously, no need to query tarallo again
		if disk.working == "yes":
			# Turn it down a notch... it's working but it may start not working soon...
			tarallo.update_features(disk.code, {"working": "maybe"})
		else:
			# Maybe badblocks failed to erase it, but it's definitely broken
			tarallo.update_features(disk.code, {"working": "no"})

	tarallo.update_features(disk.code, {"smart-data": smart_status})

systemctl_shutdown_now()
```
