### ISSUE TITLE
Fork subprocesses in background

### ISSUE THREAD

**Issue by ghost** [WEEE-Open/turbofresa#4]
Call subprocesses in background and implement a listener for system hooks that will advise wether the hard drive cleaning is finished or not.
Alternatively use some GNU tools like `pgrep` and to look for the PIDs and monitor them periodically.

**Comment by lvps** [comment]
Oooooor... we could use threads and "join" them. Or plain processes and `wait()` or `waitpid()` them. It's all already there, there are a few useful system calls or functions for thread/process synchronization, they're available in Python, the patterns to use them are well known and reasonably efficient (well, surely more efficient than polling with `pgrep`)... asd

**Comment by ghost** [comment]
I was thinking about this while I was opening this crappy issue.
Sry mate, I'm still drunk

**Comment by ghost** [comment]
But still...
The thing is that I'd like this program to be runnable:
- In verbose stdout molesto mode
- Like a daemon

But I am actually thinking about the uselessness of the first mode asd

**Comment by lvps** [comment]
From my limited experience, "server" programs often have a "do not daemonize" switch, so it may as well have some purpose we can't think of right now. Anyway I think the correct way to daemonize stuff is the `daemon()` system call, but this still needs a bit of research on our part, probably.

**Comment by e-caste** [comment]
This should have been closed for a long time now. The forking is implemented by instantiating many Task objects, one for each disk, where each instance is a Process wrapper containing the badblocks call via `subprocess.Popen()`. Closing now.
