### ISSUE TITLE
Read HDD data with lsblk

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/turbofresa#8]
This command gives everything we need in JSON format: `lsblk -J -o NAME,SERIAL,TYPE,WWN | jq "[.blockdevices[] | select(.type == \"disk\") | del(.children)]"`

Well, `SERIAL` and `WWN` is enough, but if we want to print some additional information...

The `jq` part can and maybe should be done in Python, actually. Or maybe there's a lsblk switch to exclude ODD drives, whoever implements this should check the manual.

**Comment by ghost** [comment]
Must be done here:
https://github.com/WEEE-Open/turbofresa/blob/d9e5238abeda3b0855759dd758f1d14b21c681a7/turbofresa#L90

**Comment by lvps** [comment]
Also use lsblk to identify root partition, then disk che non va piallato, not `df`
