### ISSUE TITLE
Add all HDDs as new, with full set of features

### ISSUE THREAD

**Issue by lvps** [WEEE-Open/turbofresa#9]
Edit: implement #15 before this one

Related to #7 and #8: we could also read brand, model, size and other data from lsblk and smartctl, and add new disks to tarallo automatically. It's just a POST to add it, and it could also return the item code (there's a "secret" `?loopback` parameter you can add to URLs when POSTing to get the same item back). Location should be set to the computer where the turbofresa is currently running, which should be made configurable via command line or config file.

**Comment by ghost** [comment]
This could potentially lead to duplicated hard drives if the serial numbers of already known disks don't match with the ones saved in the database.
We should either recheck all the disks or avoid to implement this feature for safe.

**Comment by lvps** [comment]
I think we should ask for confirmation like this:

> Maxtor DiamondMax Plus 8 with S/N F00B4R doesn't appear to exist in inventory. Add as new? [Y\N]

and/or add a command line parameter to enable this feature for all hard disks so it's disabled by default and/or a parameter to enable only for some serial numbers.

The reason is that if we get a new batch of hard drives, we could just slap all of the inside the piallatrice:tm: and let the turbofresa do it's job, without manual intervention, without reading serial numbers. Machines will replace us all, but that's good since reading serial numbers is the most boring job ever asd

**Comment by lvps** [comment]
Initially, for version 0.1-alpha, just add:

* type = hdd
* sn = the serial number given by smartctl or lsblk

We'll add other data later on

**Comment by e-caste** [comment]
Closed by recent commits by @TsumiYaku
